name: Build and upload

on: push

jobs:
  shipit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build .

    - name: Upload
      uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
      with:
        files: badgemagic-tool
