name: Build and upload

on:
  release:
    types:
      - created

jobs:
  shipit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build .

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: badgemagic-tool
        path: badgemagic-tool
